// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package producer

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProducer creates a new instance of MockProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProducer {
	mock := &MockProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProducer is an autogenerated mock type for the Producer type
type MockProducer struct {
	mock.Mock
}

type MockProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProducer) EXPECT() *MockProducer_Expecter {
	return &MockProducer_Expecter{mock: &_m.Mock}
}

// SendMessage provides a mock function for the type MockProducer
func (_mock *MockProducer) SendMessage(ctx context.Context, topic string, data []byte, option MessageOption) (int32, int64, error) {
	ret := _mock.Called(ctx, topic, data, option)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 int32
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, MessageOption) (int32, int64, error)); ok {
		return returnFunc(ctx, topic, data, option)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, MessageOption) int32); ok {
		r0 = returnFunc(ctx, topic, data, option)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte, MessageOption) int64); ok {
		r1 = returnFunc(ctx, topic, data, option)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, []byte, MessageOption) error); ok {
		r2 = returnFunc(ctx, topic, data, option)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockProducer_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockProducer_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - data []byte
//   - option MessageOption
func (_e *MockProducer_Expecter) SendMessage(ctx interface{}, topic interface{}, data interface{}, option interface{}) *MockProducer_SendMessage_Call {
	return &MockProducer_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, topic, data, option)}
}

func (_c *MockProducer_SendMessage_Call) Run(run func(ctx context.Context, topic string, data []byte, option MessageOption)) *MockProducer_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 MessageOption
		if args[3] != nil {
			arg3 = args[3].(MessageOption)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProducer_SendMessage_Call) Return(n int32, n1 int64, err error) *MockProducer_SendMessage_Call {
	_c.Call.Return(n, n1, err)
	return _c
}

func (_c *MockProducer_SendMessage_Call) RunAndReturn(run func(ctx context.Context, topic string, data []byte, option MessageOption) (int32, int64, error)) *MockProducer_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockProducer
func (_mock *MockProducer) Shutdown() {
	_mock.Called()
	return
}

// MockProducer_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockProducer_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MockProducer_Expecter) Shutdown() *MockProducer_Shutdown_Call {
	return &MockProducer_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MockProducer_Shutdown_Call) Run(run func()) *MockProducer_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProducer_Shutdown_Call) Return() *MockProducer_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProducer_Shutdown_Call) RunAndReturn(run func()) *MockProducer_Shutdown_Call {
	_c.Run(run)
	return _c
}
