// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package consumer

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockConsumer creates a new instance of MockConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsumer {
	mock := &MockConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConsumer is an autogenerated mock type for the Consumer type
type MockConsumer struct {
	mock.Mock
}

type MockConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsumer) EXPECT() *MockConsumer_Expecter {
	return &MockConsumer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockConsumer
func (_mock *MockConsumer) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConsumer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockConsumer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockConsumer_Expecter) Close() *MockConsumer_Close_Call {
	return &MockConsumer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockConsumer_Close_Call) Run(run func()) *MockConsumer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConsumer_Close_Call) Return(err error) *MockConsumer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConsumer_Close_Call) RunAndReturn(run func() error) *MockConsumer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Consume provides a mock function for the type MockConsumer
func (_mock *MockConsumer) Consume(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConsumer_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type MockConsumer_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConsumer_Expecter) Consume(ctx interface{}) *MockConsumer_Consume_Call {
	return &MockConsumer_Consume_Call{Call: _e.mock.On("Consume", ctx)}
}

func (_c *MockConsumer_Consume_Call) Run(run func(ctx context.Context)) *MockConsumer_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConsumer_Consume_Call) Return(err error) *MockConsumer_Consume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConsumer_Consume_Call) RunAndReturn(run func(ctx context.Context) error) *MockConsumer_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// SyncWait provides a mock function for the type MockConsumer
func (_mock *MockConsumer) SyncWait() {
	_mock.Called()
	return
}

// MockConsumer_SyncWait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncWait'
type MockConsumer_SyncWait_Call struct {
	*mock.Call
}

// SyncWait is a helper method to define mock.On call
func (_e *MockConsumer_Expecter) SyncWait() *MockConsumer_SyncWait_Call {
	return &MockConsumer_SyncWait_Call{Call: _e.mock.On("SyncWait")}
}

func (_c *MockConsumer_SyncWait_Call) Run(run func()) *MockConsumer_SyncWait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConsumer_SyncWait_Call) Return() *MockConsumer_SyncWait_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConsumer_SyncWait_Call) RunAndReturn(run func()) *MockConsumer_SyncWait_Call {
	_c.Run(run)
	return _c
}
